### ISSUE TITLE
Displayed values not aligned with underlying color representation of the phases

### ISSUE THREAD

**Issue by flo269** [mentalilll/ha-vpd-chart#10]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I'm using a leaf sensor and even though the values displayed are correct, it seems the underlying phase colors are skewed. They seem correct for the tool tip, but not for the actual current values.

**Version of the card**
Version: 1.3.5

**To Reproduce**
This is the configuration I used:
```
type: custom:ha-vpd-chart
min_temperature: 10
max_temperature: 35
min_humidity: 20
max_humidity: 100
min_height: 400
is_bar_view: false
enable_tooltip: true
enable_axes: true
enable_ghostmap: true
enable_triangle: true
enable_crosshair: true
sensors:
  - temperature: sensor.average_temperature
    humidity: sensor.average_humidity
    leaf_temperature: sensor.grow_sensors_leaf_temp_mlx
    name: ''
vpd_phases:
  - upper: 0
    className: gray-danger-zone
    color: null
  - lower: 0
    upper: 0.4
    className: under-transpiration
    color: null
  - lower: 0.4
    upper: 0.8
    className: early-veg
  - lower: 0.8
    upper: 1.2
    className: late-veg
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
  - lower: 1.6
    className: danger-zone
```

**Screenshots**
Here a screenshot comparing to [vpdchart-card](https://github.com/vpdchart/vpdchart-card)
![Screenshot](https://github.com/user-attachments/assets/845cb6a7-ea44-4ba7-8e13-2af8b7abe893)

**Expected behavior**
The values calculated and displayed to be consistent with the underlying phase colors

**Desktop:**
- Browser [firefox and safari]
- Version [128.0.3 and 17.5 (19618.2.12.11.6)]

**Smartphone:**
- Device: [iPhoneSE 3rd. gen]
- OS: [iOS17.5.1]
- Browser [Latest Home Assistant App]
