### ISSUE TITLE
leaf_temperature_offset as variable

### ISSUE THREAD

**Issue by FNLOZZIO** [mentalilll/ha-vpd-chart#11]
Good morning,

Is it possible to make "leaf_temperature_offset" linked to an external variable (ie entity state)?

I am trying to run this:
```
type: custom:ha-vpd-chart
...
leaf_temperature_offset: input_number.leaf_temperature_offset
sensors:
  - temperature: sensor.temperature
    humidity: sensor.humidity
    name: room
...
```
instead of this:
```
type: custom:ha-vpd-chart
...
leaf_temperature_offset: 2
sensors:
  - temperature: sensor.temperature
    humidity: sensor.temperature
    name: room
...
```
without any success.
