### ISSUE TITLE
Will block page on mobile

### ISSUE THREAD

**Issue by garv3** [mentalilll/ha-vpd-chart#15]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Since one of the latest updates (do not know which one) adding the card to a dashboard page will block the page from being loaded on mobile. The pages loads on desktop but not on a smart phone where it instead shows an empty page as if not cards had been added.

**Version of the card**
Version: 1.4.9

**To Reproduce**
This is the configuration I used:
```
type: custom:ha-vpd-chart
air_text: Temp.
rh_text: RF
min_temperature: 5
max_temperature: 35
min_humidity: 10
max_humidity: 100
min_height: 200
is_bar_view: false
enable_tooltip: false
enable_axes: false
enable_ghostmap: false
enable_triangle: false
sensors:
  - temperature: sensor.luftsensor_arbeitszimmer_temperature
    humidity: sensor.luftsensor_arbeitszimmer_humidity
    name: Growbox
leaf_temperature_offset: 2
kpa_text: VPD
vpd_phases:
  - upper: 0.4
    className: under-transpiration
    lower: -0.59
    color: '#1a6c9c'
  - lower: 0.4
    upper: 0.8
    className: early-veg
    color: '#22ab9c'
  - lower: 0.8
    upper: 1.2
    className: late-veg
    color: '#9cc55b'
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
    color: '#e7c12b'
  - lower: 1.6
    className: danger-zone
    upper: 4.47
    color: '#ce4234'
enable_crosshair: false
ghostmap_hours: 1
enable_fahrenheit: false
calculateVPD: >-
  const VPleaf = 610.7 * Math.exp(17.27 * Tleaf / (Tleaf + 237.3)) / 1000;

  const VPair = 610.7 * Math.exp(17.27 * Tair / (Tair + 237.3)) / 1000 * RH /
  100;

  return VPleaf - VPair;
```
**Desktop (please complete the following information):**
- Browser Edge
- Version latest

**Smartphone (please complete the following information):**
- Device: Xiaomi Mi Mix 3
- OS: Android
- Browser: HA Client
- Version: latest
