### ISSUE TITLE
Values showing up at the wrong spot of the chart

### ISSUE THREAD

**Issue by jayme-github** [mentalilll/ha-vpd-chart#18]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The tooltip is showing correct values, but the white dot seems to be placed in the wrong area of the chart (see screenshot). 

**Version of the card**
Version: 1.5.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:ha-vpd-chart
sensors:
  - temperature: sensor.sonoff_snzb_02_1_temperature
    humidity: sensor.sonoff_snzb_02_1_humidity_calibrated
    leaf_temperature: sensor.sonoff_snzb_02_1_temperature
    name: Sonoff
vpd_phases:
  - upper: 0
    className: gray-danger-zone
    color: '#999999'
  - lower: 0
    upper: 0.4
    className: under-transpiration
    color: '#1a6c9c'
  - lower: 0.4
    upper: 0.8
    className: early-veg
    color: '#22ab9c'
  - lower: 0.8
    upper: 1.2
    className: late-veg
    color: '#9cc55b'
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
    color: '#e7c12b'
  - lower: 1.6
    className: danger-zone
    color: '#ce4234'
is_bar_view: false
min_temperature: 5
max_temperature: 35
min_humidity: 10
max_humidity: 90
min_height: 200
leaf_temperature_offset: 2
enable_tooltip: true
air_text: Air
rh_text: RH
kpa_text: kPa
enable_axes: true
enable_ghostclick: true
enable_ghostmap: true
enable_triangle: false
enable_crosshair: true
enable_fahrenheit: false
enable_zoom: true
enable_show_always_informations: true
enable_legend: false
ghostmap_hours: 24
unit_temperature: °C
```

**Screenshots**
![image](https://github.com/user-attachments/assets/b9cd0a4a-6180-4383-996c-4ed966d824eb)

**Desktop (please complete the following information):**
- Browser: Chrome 128.0.6613.119, Firefox 129.0.2
