### ISSUE TITLE
Provide VPD sensor to the system  

### ISSUE THREAD

**Issue by BubiBalboa** [mentalilll/ha-vpd-chart#20]
I'd love to have the current VPD value available in other parts of HA to use in alerts and automations. 

I think it makes sense for this integration to be the one "VPD provider" for the system. I assume this would be done by exposing the VPD value the chart uses as a sensor. 

It's easy enough to create a helper that acts as a VPD sensor but it's not exactly ideal to have the system calculate the same value twice. I had it happen that something changed and the VPD chart and the helper sensor didn't match anymore. Makes troubleshooting more complicated. That's why it would be nice to have just one VPD value in the system, provided by this integration. 

Thank you for creating this software. Super useful.

**Comment by Xsev1** [comment]
+1 pls

**Comment by mentalilll** [comment]
To use VPD Sensor right now, you can do the following Steps:
Add the Following Sensor Templates to your Configuration.yaml you need to Change the sensor.cabinet_ sensors.

If you use a Infrared Sensor you should use **{% set LT = states('sensor.infrared_sensor')|float %}** instead of  **{% set LT = states('sensor.cabinet_bme280_temperature')|float - 2 %}**
```yaml

sensor:
  - platform: template
    sensors:
      gd_vpd:
        icon_template: 'mdi:water-percent'
        unit_of_measurement: kPa
        value_template: |

          {% set T = states('sensor.cabinet_bme280_temperature')|float %}
          {% set RH = states('sensor.cabinet_bme280_humidity')|float %}
          {% set SVP = 0.61078 * e ** (T / (T + 237.3) * 17.2694) %}
          {% set VPD = SVP * ((100 - RH) / 100) %}
          {{ VPD | round(2) }}
  - platform: template
    sensors:
      gd_vpd_leaf:
        icon_template: 'mdi:leaf'
        unit_of_measurement: kPa
        value_template: >
          {% set T = states('sensor.cabinet_bme280_temperature')|float %}
          {% set RH = states('sensor.cabinet_bme280_humidity')|float %}
          {% set LT = states('sensor.cabinet_bme280_temperature')|float - 2 %} # or {% set LT = states('sensor.infrarot_sensor')|float %} 
          {% set ASVP = 0.61078 * e ** (T / (T + 237.3) * 17.2694) %}
          {% set LSVP = 0.61078 * e ** (LT / (LT + 237.3) * 17.2694) %}
          {% set LVPD = LSVP - (ASVP * RH / 100) %}

          {{ LVPD | round(2) }}
```

So you can have the Value on your system right now, without need to wait for my Work here :).

![Image](https://github.com/user-attachments/assets/31f0398f-2068-4373-b3d5-f3fd46ce638f)

You also can set up multiple sensor like I did :).

 I currently try to figure out how i could create that template from JavaScript side. Maybe no python plugin needed :P
