### ISSUE TITLE
Ghostmap is broken with v2.1.0-dev2

### ISSUE THREAD

**Issue by NoXPhasma** [mentalilll/ha-vpd-chart#27]
**Checklist**

- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser
- [x] I cleared the .gz files from www/community/ha-vpd-chart folder
- [x] I have read the current documentation

**Describe the bug**
The ghostmap overlay is misplaced, has a background and a scrollbar in the browser and app. 

**Version of the card**
Version:  v2.1.0-dev2

**Version of HomeAssistant**
Version: 2025.4.3

**What is the installation method of HomeAssistant? OS, Docker**
What is the installation method of HomeAssistant?: Docker

**To Reproduce**
This is the configuration I used:

```yaml
type: horizontal-stack
cards:
  - type: custom:ha-vpd-chart
    sensors:
      - temperature: sensor.growbox_temperature_1
        humidity: sensor.growbox_humidity_1
        name: 1
    enable_ghostmap: true
    kpa_text: ""
    air_text: ""
    rh_text: ""
    enable_axes: true
    vpd_phases:
      - upper: 0
        className: G
        color: "#999999"
      - lower: 0
        upper: 0.4
        className: T
        color: "#1a6c9c"
      - lower: 0.4
        upper: 0.8
        className: EV
        color: "#22ab9c"
      - lower: 0.8
        upper: 1.2
        className: LV
        color: "#9cc55b"
      - lower: 1.2
        upper: 1.6
        className: MF
        color: "#e7c12b"
      - lower: 1.6
        className: D
        color: "#ce4234"
    is_bar_view: false
    max_temperature: 30
    max_humidity: 90
    enable_tooltip: true
    enable_ghostclick: true
    enable_triangle: true
    enable_crosshair: true
    enable_fahrenheit: false
    enable_zoom: true
    enable_show_always_informations: true
    enable_legend: true
    ghostmap_hours: 24
    unit_temperature: °C
    min_height: 108
    min_humidity: 35
    min_temperature: 10
    leaf_temperature_offset: 2
  - type: custom:ha-vpd-chart
    sensors:
      - temperature: sensor.growbox_temperature_2
        humidity: sensor.growbox_humidity_2
        name: 2
    enable_ghostmap: true
    kpa_text: ""
    air_text: ""
    rh_text: ""
    leaf_temperature_offset: 2
    vpd_phases:
      - upper: 0
        className: G
        color: "#999999"
      - lower: 0
        upper: 0.4
        className: T
        color: "#1a6c9c"
      - lower: 0.4
        upper: 0.8
        className: EV
        color: "#22ab9c"
      - lower: 0.8
        upper: 1.2
        className: LV
        color: "#9cc55b"
      - lower: 1.2
        upper: 1.6
        className: LF
        color: "#e7c12b"
      - lower: 1.6
        className: D
        color: "#ce4234"
    is_bar_view: false
    min_temperature: 10
    max_temperature: 30
    min_humidity: 30
    max_humidity: 90
    min_height: 108
    enable_tooltip: true
    enable_axes: true
    enable_ghostclick: true
    enable_triangle: true
    enable_crosshair: true
    enable_fahrenheit: false
    enable_zoom: true
    enable_show_always_informations: true
    enable_legend: true
    ghostmap_hours: 24
    unit_temperature: °C
```

**Screenshots**
![Image](https://github.com/user-attachments/assets/406b1282-b0ad-4451-b2d6-6a953e34aa8b)

**Expected behavior**
The overlay should be positioned properly, without a background and scrollbar.

**Desktop (please complete the following information):**

- Browser Chromium
- Version 136.0.7

- Browser Firefox
- Version 138.0.1

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S21
- OS: Android 14

**Additional context**

**Comment by einfachuli** [comment]
You should update your configuration. The section sensors must now be rooms. So rename sensors: to rooms:

**Comment by NoXPhasma** [comment]
I did that in the meantime as well, but it did not change that I have that overlay. 

```
type: custom:ha-vpd-chart
rooms:
  - temperature: sensor.growbox_temperature_1
    humidity: sensor.growbox_humidity_1
    name: 1
vpd_phases:
  - upper: 0
    className: G
    color: "#999999"
  - lower: 0
    upper: 0.4
    className: T
    color: "#1a6c9c"
  - lower: 0.4
    upper: 0.8
    className: EV
    color: "#22ab9c"
  - lower: 0.8
    upper: 1.2
    className: LV
    color: "#9cc55b"
  - lower: 1.2
    upper: 1.6
    className: MF
    color: "#e7c12b"
  - lower: 1.6
    className: D
    color: "#ce4234"
is_bar_view: false
min_height: 100
leaf_temperature_offset: 2
enable_tooltip: true
air_text: ""
leaf_text: Leaf
rh_text: ""
kpa_text: ""
enable_axes: true
enable_ghostclick: true
enable_ghostmap: true
enable_triangle: true
enable_crosshair: true
enable_zoom: true
enable_show_always_informations: true
enable_legend: true
ghostmap_hours: 24
antialiasing: 5
unit_temperature: °C
max_temperature: 32
max_humidity: 90
enable_fahrenheit: false
min_humidity: 35
min_temperature: 16
```
