### ISSUE TITLE
Version 1.2.1 does not work properly in the Android App, Firefox and Chromium

### ISSUE THREAD

**Issue by NoXPhasma** [mentalilll/ha-vpd-chart#4]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
There are several bugs with version 1.2.1 in Android App, Firefox and Chromium.

With Firefox the graph looks way off, some values are wrong calculated and the performance is abysmal.  I have the exact same behavior win the Android app. 

In Chromium, only the first card gets a colorful background. Performance and values look fine. 

These bugs are not present in 1.2.0.

**Version of the card**
Version: 1.2.1

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:ha-vpd-chart
air_text: Temp.
min_humidity: 30
max_humidity: 80
min_temperature: 10
max_temperature: 35
sensors:
  - temperature: sensor.growbox_temperature
    humidity: sensor.growbox_humidity
    name: Luft
    leaf_temperature_offset: 0

```

**Screenshots**
[Firefox Screenshot](https://github.com/mentalilll/ha-vpd-chart/assets/7719590/ee7f8f6a-eca9-47dc-9d65-35679d09d6a9)
[Android App](https://github.com/mentalilll/ha-vpd-chart/assets/7719590/32293414-e69d-4f51-aad9-2be31cf76a6e)
[Chromium Screenshot](https://github.com/mentalilll/ha-vpd-chart/assets/7719590/620d20e8-731c-4db5-b33a-d69c93cad69a)

**Desktop (please complete the following information):**
- Browser firefox 126, chromium 125

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S21
- OS: Android 14

**Additional context**
