### ISSUE TITLE
Chart View does not update when sensor values change.

### ISSUE THREAD

**Issue by garv3** [mentalilll/ha-vpd-chart#6]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
The chart does not update while open. The bar view does!
Se the latest value in the bar view but chart stuck on values from when the page was loaded:
![image](https://github.com/mentalilll/ha-vpd-chart/assets/6571889/780e7b46-e67c-496d-a1af-c0de7ceb9179)

**Version of the card**
Version: 1.2.4

**To Reproduce**
This is the configuration I used:
```
type: custom:ha-vpd-chart
air_text: Temp.
rh_text: RF
min_temperature: 5
max_temperature: 35
min_humidity: 10
max_humidity: 100
min_height: 200
is_bar_view: false
enable_tooltip: true
enable_axes: false
enable_ghostmap: false
enable_triangle: true
sensors:
  - temperature: sensor.luftsensor_arbeitszimmer_temperature
    humidity: sensor.luftsensor_arbeitszimmer_humidity
    name: Growbox
leaf_temperature_offset: 2
kpa_text: VPD
vpd_phases:
  - upper: 0.4
    className: under-transpiration
  - lower: 0.4
    upper: 0.8
    className: early-veg
  - lower: 0.8
    upper: 1.2
    className: late-veg
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
  - lower: 1.6
    className: danger-zone
```

**Screenshots**
see above

**Expected behavior**
The chart should update on any sensor value change as the bar view does.

**Desktop (please complete the following information):**
- Browser [Edge]
- Version [125.0.2535.51]

**Smartphone (please complete the following information):**
- Device: [Xiaomi Mi Mix 3]
- OS: [Android]
- Browser [HA Companion App]
- Version [2024.4.1-full]
