### ISSUE TITLE
CPU usage extremely high + Map borked

### ISSUE THREAD

**Issue by dzatoah** [mentalilll/ha-vpd-chart#7]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**
The whole browser gets laggy af because CPU is busy drawing stuff, I think. And see pic:
![grafik](https://github.com/mentalilll/ha-vpd-chart/assets/16420080/d6f3011d-96e8-4b9f-9b11-85f02dc96afd)

**Version of the card**
Version: main
Last known working version: 1.2.0

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:ha-vpd-chart
air_text: Temp
sensors:
  - temperature: sensor.zelt_t_combined
    humidity: sensor.zelt_rh_combined
    name: Luft
```

**Desktop (please complete the following information):**
- Browser: Firefox
- Version 126.0.1
