### ISSUE TITLE
Option for Fahrenheit temp

### ISSUE THREAD

**Issue by FunkeyMonkey** [mentalilll/ha-vpd-chart#8]
**Checklist**
- [x] I am running the latest version of the card
- [x] I checked if there isn't another feature request opened with the same request
- [ ] I checked that the feature is not already available in the `dev` branch

**Is your feature request related to a problem? Please describe.**
Displays in C

**Describe the solution you'd like**
Would love a toggle to switch between C and F
**Describe alternatives you've considered**
If toggle not an option than a way to hardcode it
**Additional context**

Looks like the bar view is showing the correct temp but labels it as C. It is 59F at the sensor location
![image](https://github.com/mentalilll/ha-vpd-chart/assets/13045972/cbe333a9-edf0-4ab8-a8c6-ed7c74ace9d8)

**Comment by mentalilll** [comment]
Comes with the upcoming update :).

**Comment by FunkeyMonkey** [comment]
Awesome thanks! One other small issue i'm having, trying to use the HaVpdChart config. I use the same sensors as the bar and chart but it doesn't load for some reason. It makes my dashboard tab go blank and have to refresh time or two to get it back and then it just shows like this under edit. Any thoughts?
![image](https://github.com/mentalilll/ha-vpd-chart/assets/13045972/3d87850e-ac45-4858-a8fc-ea66f287e39a)

```
type: custom:ha-vpd-chart
air_text: Temp.
rh_text: r.H.
min_temperature: 5
max_temperature: 35
min_humidity: 10
max_humidity: 100
min_height: 200
is_bar_view: true
enable_tooltip: true
enable_axes: true
enable_ghostmap: true
enable_triangle: false
enable_crosshair: true
sensors:
  - temperature: sensor.esphome_web_158a7c_temperature_sht40
    humidity: sensor.esphome_web_158a7c_humidity_sht40
    leaf_temperature: sensor.esphome_web_158a7c_temperature_bmp280
    name: Tent 1
  - temperature: sensor.esphome_web_166e48_temperature_sht40
    humidity: sensor.esphome_web_166e48_humidity_sht40
    vpd: null
    name: Tent 2
vpd_phases:
  - upper: 0
    className: gray-danger-zone
    color: null
  - lower: 0
    upper: 0.4
    className: under-transpiration
    color: null
  - lower: 0.4
    upper: 0.8
    className: early-veg
  - lower: 0.8
    upper: 1.2
    className: late-veg
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
  - lower: 1.6
    className: danger-zone
calculateVPD: |2-
          const VPleaf = 610.7 * Math.exp(17.27 * Tleaf / (Tleaf + 237.3)) / 1000; 
          const VPair = 610.7 * Math.exp(17.27 * Tair / (Tair + 237.3)) / 1000 * RH / 100;
          return VPleaf - VPair;
```
