### ISSUE TITLE
Different values between Tooltip and permanently displayed value

### ISSUE THREAD

**Issue by NordFreak** [mentalilll/ha-vpd-chart#9]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Hello, I have the problem that the display shows a different value than the tooltip. According to my research, the values of the tooltip are correct.

Where does the difference between the permanent display and the tooltip come from?

To explain, the tooltip value comes from the same marker as the main display (with a slight deviation in the initial values because I can’t select it precisely with the mouse).

But the fact is that I have a deviation of 0.35 kPa. Now I’m looking for a solution to my problem.

**Version of the card**
Version:1.3.5

**To Reproduce**
This is the configuration I used:
```
type: custom:ha-vpd-chart
sensors:
  - temperature: sensor.growbox_temperatur
    humidity: sensor.growbox_luftfeuchtigkeit
    name: ''
    leaf_temperature: sensor.growbox_temperatur
enable_tooltip: true
enable_ghostmap: true
enable_axes: true
enable_triangle: true
is_bar_view: false
min_humidity: 40
min_temperature: 15
max_temperature: 35
min_height: 300
max_humidity: 90
vpd_phases:
  - lower: 0
    upper: 0
    className: gray-danger-zone
    color: '#999999'
  - lower: 0
    upper: 0.8
    className: under-transpiration
    color: '#1a6c9c'
  - lower: 0.8
    upper: 1
    className: early-veg
    color: '#22ab9c'
  - lower: 1
    upper: 1.2
    className: late-veg
    color: '#9cc55b'
  - lower: 1.2
    upper: 1.6
    className: mid-late-flower
    color: '#e7c12b'
  - lower: 1.6
    className: danger-zone
    color: '#ce4234'

```

**Screenshots**
![grafik](https://github.com/mentalilll/ha-vpd-chart/assets/125671870/104aeecc-b763-44d2-bbca-8cc6f24b705a)

**Expected behavior**
I would expect that both the permanently displayed kPa value matches the tooltip value. The VPD phases also correspond to the tooltip. It’s just that the permanently shown value doesn’t match.

**Desktop (please complete the following information):**
No problem of a device or browser, as the problem exists on all devices.

**Smartphone (please complete the following information):**
No problem of a device or browser, as the problem exists on all devices.

**Additional context**
It's a great addon, if I can get it fixed. many thanks for the great work.
